src/project_x/urls.py
from django.contrib import admin
from django.urls import path
from business import views
from django.views.generic import TemplateView
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home),
    path('emp', views.emp, name = "business_create"),  
    path('show',views.show),  
    path('edit/<int:id>', views.edit),  
    path('update/<int:id>', views.update, name = "business_update"),  
    path('delete/<int:id>', views.destroy, name = "business_delete"), 
    path('search/', views.search, name='search'), 
   ]

src/business/models.py
from django.db import models

# Create your models here.

class Business(models.Model):  
    name = models.CharField(max_length=100)  
    email = models.EmailField()  
    contact = models.CharField(max_length=15) 
    address = models.CharField(max_length=500)
    ownername = models.CharField(max_length=100)
    NumberofEmployees = models.IntegerField()

    class Meta:  
        db_table = "business"  

src/business/forms.py
from django import forms  
from business.models import Business  
class BusinessForm(forms.ModelForm):  
    class Meta:  
        model = Business  
        fields = "__all__"  

src/business/views.py
from django.shortcuts import render, redirect  
from business.forms import BusinessForm  
from business.models import Business

def home(request):
    return render(request,'home.html')

    
def emp(request):  
    if request.method == "POST": 
        form = BusinessForm(request.POST)  
        if form.is_valid():  
            try:  
                form.save()  
                return redirect('/show')  
            except:  
                pass
    else:
        form = BusinessForm()  
    return render(request,'index.html',{'form':form})

def show(request):  
    businesses = Business.objects.all()
    return render(request,"show.html",{'businesses':businesses}) 

def edit(request, id):  
    business = Business.objects.get(id=id)  
    return render(request,'edit.html', {'business':business})

def update(request, id):  
    business = Business.objects.get(id=id)  
    form = BusinessForm(request.POST, instance = business)  
    if form.is_valid():
        form.save()
        return redirect("/show")
    return render(request, 'edit.html', {'business': business})  

def destroy(request, id):  
    business = Business.objects.get(id=id)  
    business.delete()  
    return redirect("/show") 

def search(request):
    query = request.GET.get('query')
    
    if query:
        businesses = Business.objects.filter(name__icontains=query)  # Modify this filter condition as needed
    else:
        businesses = Business.objects.all()

    return render(request, 'search_results.html', {'businesses': businesses, 'query': query})

src/business/templates/edit.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Index</title>  
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    {% load static %}  
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
</head>  
<body>  
<form method="POST" class="post-form" action="/update/{{business.id}}">  
        {% csrf_token %}  
    <div class="container">  
<br>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <h3>Update Details</h3>  
    </div>  
  </div>  
  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Business Name:</label>  
    <div class="col-sm-4">  
        <input type="text" name="name" id="id_name" required maxlength="100" value="{{ business.name }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Business Email:</label>  
    <div class="col-sm-4">  
        <input type="email" name="email" id="id_email" required maxlength="254" value="{{ business.email }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Business Contact:</label>  
    <div class="col-sm-4">  
        <input type="text" name="contact" id="id_contact" required maxlength="15" value="{{ business.contact }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Business Contact:</label>  
    <div class="col-sm-4">  
        <input type="text" name="address" id="id_address" required maxlength="15" value="{{ business.address }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Business Contact:</label>  
    <div class="col-sm-4">  
        <input type="text" name="ownername" id="id_ownername" required maxlength="15" value="{{ business.ownername }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Business Contact:</label>  
    <div class="col-sm-4">  
        <input type="text" name="NumberofEmployees" id="id_NumberofEmployees" required maxlength="15" value="{{ business.NumberofEmployees }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <button type="submit" class="btn btn-success">Update</button>  
    </div>  
  </div>  
    </div>  
</form>  
</body>  
</html>  

src/business/templates/home.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Index</title>  
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    {% load static %}  
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
</head>  
<body>  

    <div class="container m-5">
        <center><a href="/show" class="btn btn-primary">Show Record</a></center> 
    </div>

</body>
</html>

src/business/templates/index.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Index</title>  
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    {% load static %}  
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
</head>  
<body>  
<form method="POST" class="post-form" action="/emp">  
        {% csrf_token %}  
    <div class="container">  
<br>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <h3>Enter Details</h3>  
    </div>  
  </div>  
 
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Business Name:</label>  
    <div class="col-sm-4">  
      {{ form.name }}  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Business Email:</label>  
    <div class="col-sm-4">  
      {{ form.email }}  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Business Contact:</label>  
    <div class="col-sm-4">  
      {{ form.contact }}  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Business Address:</label>  
    <div class="col-sm-4">  
      {{ form.address }}  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Owner Name:</label>  
    <div class="col-sm-4">  
      {{ form.ownername }}  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Number of Employees:</label>  
    <div class="col-sm-4">  
      {{ form.NumberofEmployees }}  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <button type="submit" class="btn btn-primary">Submit</button>  
    </div>  
  </div>  
    </div>  
</form>  
</body>  
</html> 

src/business/templates/search_results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Search Results</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
</head>
<body>
<h2>Search Results</h2>
<p>Search Query: <strong>{{ query }}</strong></p>

<table class="table table-striped table-bordered table-sm">
    <thead class="thead-dark">
    <tr>
        <th>Business Name</th>
        <th>Business Email</th>
        <th>Business Contact</th>
        <th>Actions</th>
    </tr>
    </thead>
    <tbody>
    {% for business in businesses %}
        <tr>
            <td>{{ business.name }}</td>
            <td>{{ business.email }}</td>
            <td>{{ business.contact }}</td>
            <td>
                <a href="/edit/{{ business.id }}"><span class="glyphicon glyphicon-pencil">Edit</span></a>
                <a href="/delete/{{ business.id }}">Delete</a>
            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>
<br>
<br>
<center><a href="/emp" class="btn btn-primary">Add New Record</a></center>
</body>
</html>

src/business/templates/show.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Business Records</title>  
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    {% load static %}  
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>  
  
</head>  
<body>  
    <div class="container m-5">
    <form method="GET" action="{% url 'search' %}" class="p-3">
        <input type="text" name="query" placeholder="Search...">
        <button type="submit">Search</button>
      </form>
      {% if query %}
  <!-- Display search results -->
  {% include 'search_results.html' %}
{% else %}
<table class="table table-striped table-bordered table-sm">  
    <thead class="thead-dark">  
    <tr>  
         
        <th>Business Name</th>  
        <th>Business Email</th>  
        <th>Business Contact</th>  
        <th>Actions</th>  
    </tr>  
    </thead>  
    <tbody>  
{% for Business in businesses %}  
    <tr>  
       
        <td>{{ Business.name }}</td>  
        <td>{{ Business.email }}</td>  
        <td>{{ Business.contact }}</td>  
        <td>  
            <a href="/edit/{{ Business.id }}"><span class="glyphicon glyphicon-pencil" >Edit</span></a>  
            <a href="/delete/{{ Business.id }}">Delete</a>  
        </td>  
    </tr>  
{% endfor %}  
    </tbody>  
</table>  
{% endif %}

<br>  
<br>  
<center><a href="/emp" class="btn btn-primary">Add New Record</a></center>  
    </div>
</body>  
</html>  